id: P10CA06B9
initial_creation_type: input
source_metadata:
  title: 'Asaṅga/Maitreya: Ratnagotravibhāga'
  language: en
  volumes:
    d8909c32b4e44aa797ec40d372af3589:
      title: CIII_XIV. General Characteristics Of The Buddha’s Properties
      base_file: CIII_XIV. General Characteristics Of The Buddha’s Properties.txt
      work_id: W730F4848
    ca39ae70a7e34ad096eb369d10d2f27c:
      title: CIII_XV. 64 Properties of the Buddha
      base_file: CIII_XV. 64 Properties of the Buddha.txt
      work_id: W3341A66A
    2fc6cd0e68e24d53b16917303ca5e2e3:
      title: CII_XII. General Characteristics of the Reality Free from Pollutions
      base_file: CII_XII. General Characteristics of the Reality Free from Pollutions.txt
      work_id: W3CEBB228
    f1ddc4b8f52640c7bf3f73566d8490a7:
      title: CII_XIII. 8 Points on the Undefiled Reality
      base_file: CII_XIII. 8 Points on the Undefiled Reality.txt
      work_id: W6CA4F5D7
    432208d0838c494a88e76b3fd216d3ae:
      title: CIV_XVI. General Characteristics of the Acts of the Buddha
      base_file: CIV_XVI. General Characteristics of the Acts of the Buddha.txt
      work_id: WFE4FD98C
    7b1a146831a84ea29b3ca2f4bc98af26:
      title: CIV_XVII. 9 Illustrations of the Buddha’s Acts
      base_file: CIV_XVII. 9 Illustrations of the Buddha’s Acts.txt
      work_id: W22DAA09E
    b549d4c1de5146aa85ca95d24827967c:
      title: CI_I. Introduction
      base_file: CI_I. Introduction.txt
      work_id: WA286A258
    932f872a10fa4b12ac43045309696dfc:
      title: CI_II. The Jewel of the Buddha
      base_file: CI_II. The Jewel of the Buddha.txt
      work_id: W576C63B5
    a28b45107dfb4fba86c9ccc4e0acdc89:
      title: CI_III. The Jewel of the Doctrine
      base_file: CI_III. The Jewel of the Doctrine.txt
      work_id: WB767AC9C
    39639384110443d7b96c7063f761f580:
      title: CI_IV. The Jewel of the Community
      base_file: CI_IV. The Jewel of the Community.txt
      work_id: WB808B9F1
    66017a3a46084051b612a5a026016408:
      title: CI_IX. The 9 Illustrations on the Germ Covered with Defilements
      base_file: CI_IX. The 9 Illustrations on the Germ Covered with Defilements.txt
      work_id: W907768A2
    dca397f0a20f429ab644952aa42fcf02:
      title: CI_V. The Three Jewels as Refuges
      base_file: CI_V. The Three Jewels as Refuges.txt
      work_id: W6C174A16
    3030ec101efd4724b0e655f90c49f920:
      title: CI_VI. The Germ Of Three Jewels In Four Aspects
      base_file: CI_VI. The Germ Of Three Jewels In Four Aspects.txt
      work_id: WE866BD2E
    5711d0e043eb425b8f6cab5b8d01bf04:
      title: 'CI_VII. The Sermon: All Living Beings are possessed of The Matrix of
        the Tathāgata'
      base_file: 'CI_VII. The Sermon: All Living Beings are possessed of The Matrix
        of the Tathāgata.txt'
      work_id: W6C277D28
    030b3faa35de480f9db7cc3d3f0c9dc2:
      title: CI_VIII. Analysis of the Germ from 10 Points of View
      base_file: CI_VIII. Analysis of the Germ from 10 Points of View.txt
      work_id: WBF14EAE6
    d5f929de58674602afa45009264efa35:
      title: CI_X. The Essential Characteristics of the Matrix of the Tathāgata
      base_file: CI_X. The Essential Characteristics of the Matrix of the Tathāgata.txt
      work_id: W9C4BDB44
    d783be44e4a64390829cfdeb9ddf4a50:
      title: CI_XI. The Purpose of Instruction
      base_file: CI_XI. The Purpose of Instruction.txt
      work_id: W5C98D2C3
    9d4ef775464e49f38b02a91dff85e9c8:
      title: CV_XVIII. The Merits of Having Faith in the Doctrine of the Essence of
        Buddhahood
      base_file: CV_XVIII. The Merits of Having Faith in the Doctrine of the Essence
        of Buddhahood.txt
      work_id: W95A890D8
    7c84ff53bcdb4024b4851ed051c5d1f5:
      title: Colophon
      base_file: Colophon.txt
      work_id: W651885AB
    c17158f084cf4706857bd78de31c78cb:
      title: Preface
      base_file: Preface.txt
      work_id: W0F4C4454
    1d00638e572742c1803a399258f6c6be:
      title: Title
      base_file: Title.txt
      work_id: W1141D1D8
  chapter_to_tile:
    CI: 'Chapter I: The Matrix of the Tathāgata'
    CII: 'Chapter II: The Matrix of the Tathāgata'
    CIII: 'Chapter III: The Properties of the Buddha'
    CIV: 'Chapter IV: The Acts of The Buddha'
    CV: 'Chapter V: The Merits of Faith'
created_at: '2022-03-01T23:02:33.468195'
last_modified_at: '2022-03-01T23:02:33.468203'
